### ISSUE TITLE
Waiting Dialog en Edit Campaign

### ISSUE THREAD

**Issue by eliasconx** [SmartNodo/sam#1]
Cerrar waiting dialog en edit campaign hasta que se carguen las 3 tabls de Info, Schedule y Sales Agent ya que se quita al momento de cargar el primer tab y cuando interactúas con crear un nuevo sales agent no obtiene los datos de Schedule ya que aún no está cargada.

**Comment by leohvil89** [comment]
comenzando a resolver! @eliasconx
